# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='m', help_text='User gender', max_length=1),
        ),
    ]
