# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190306_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
